In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv('새마을금고_서울강남구.csv', encoding='euc-kr')
d2 = pd.read_csv('새마을금고_서울강동구.csv', encoding='euc-kr')
d3 = pd.read_csv('새마을금고_서울강북구.csv', encoding='euc-kr')
d4 = pd.read_csv('새마을금고_서울강서구.csv', encoding='euc-kr')
d5 = pd.read_csv('새마을금고_서울관악구.csv', encoding='euc-kr')
d6 = pd.read_csv('새마을금고_서울광진구.csv', encoding='euc-kr')
d7 = pd.read_csv('새마을금고_서울구로구.csv', encoding='euc-kr')
d8 = pd.read_csv('새마을금고_서울금천구.csv', encoding='euc-kr')
d9 = pd.read_csv('새마을금고_서울노원구.csv', encoding='euc-kr')
d10 = pd.read_csv('새마을금고_서울도봉구.csv', encoding='euc-kr')
d11 = pd.read_csv('새마을금고_서울동대문구.csv', encoding='euc-kr')
d12 = pd.read_csv('새마을금고_서울동작구.csv', encoding='euc-kr')
d13 = pd.read_csv('새마을금고_서울마포구.csv', encoding='euc-kr')
d14 = pd.read_csv('새마을금고_서울서대문구.csv', encoding='euc-kr')
d15 = pd.read_csv('새마을금고_서울서초구.csv', encoding='euc-kr')
d16 = pd.read_csv('새마을금고_서울성동구.csv', encoding='euc-kr')
d17 = pd.read_csv('새마을금고_서울성북구.csv', encoding='euc-kr')
d18 = pd.read_csv('새마을금고_서울송파구.csv', encoding='euc-kr')
d19 = pd.read_csv('새마을금고_서울양천구.csv', encoding='euc-kr')
d20 = pd.read_csv('새마을금고_서울영등포구.csv', encoding='euc-kr')
d21 = pd.read_csv('새마을금고_서울용산구.csv', encoding='euc-kr')
d22 = pd.read_csv('새마을금고_서울은평구.csv', encoding='euc-kr')
d23 = pd.read_csv('새마을금고_서울종로구.csv', encoding='euc-kr')
d24 = pd.read_csv('새마을금고_서울중구.csv', encoding='euc-kr')
d25 = pd.read_csv('새마을금고_서울중랑구.csv', encoding='euc-kr')

In [4]:
print(d1.shape,d2.shape)

(11, 4) (9, 4)

In [6]:
full_df = pd.concat([d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17,
                    d18, d19, d20, d21, d22, d23, d24, d25], axis = 0)

In [7]:
full_df.head(20)

            name category             address           tel
0         세종(본점)       직장  서울 강남구 봉은사로114길 20  02-2145-9933
1      하이트맥주(본점)       직장     서울 강남구 영동대로 714  02-3219-0294
2   서울개인택시조합(강남)       지역      서울 강남구 개포로 636  02-2057-0540
3        청담동(본점)       지역      서울 강남구 삼성로 753   02-542-3127
4         대왕(본점)       지역    서울 강남구 밤고개로34길 4  02-2226-6804
5         대왕(일원)       지역   서울 강남구 양재대로55길 15  02-2226-8284
6       강남중앙(본점)       지역    서울 강남구 선릉로64길 15   02-553-8996
7       강남중앙(역삼)       지역      서울 강남구 도곡로 173  02-2052-1114
8       강남영동(본점)       지역   서울 강남구 언주로134길 21   02-516-8900
9     한국무역협회(본점)       직장     서울 강남구 영동대로 511  02-6000-5088
10       포스코(본점)       직장     서울 강남구 테헤란로 440  02-3457-3863
0   서울개인택시조합(강동)       지역      서울 강동구 명일로 230   02-426-2933
1       서울강동(본점)       지역    서울 강동구 천호대로 1461   02-429-1183
2       서울강동(고덕)       지역   서울 강동구 동남로82길 107   02-429-1600
3       서울강동(강일)       지역   서울 강동구 아리수로97길 20   02-442-5507
4       서울강동(성내)       지역      서울 강동구 풍성로 161   02-475-6464
5         천호(본점)       지역     서울 강동구 구천면로 290   02-482-3730
6         천호(암사)       지역       서울 강동구 암사길 27  02-6925-4147
7        신강동(본점)       지역    서울 강동구 천호대로 1176   02-488-2101
8        신강동(명일)       지역  서울 강동구 양재대로138길 32  02-3428-7384

In [9]:
full_df.to_csv('새마을금고_서울통합.csv', index = False, encoding='euc-kr')